version: "3"

services:
  server:
    hostname: fullstack-frontend
    container_name: fullstack-frontend
    restart: unless-stopped
    env_file:
      - .env
    build: .
    ports:
      - "${COMPOSE_EXPOSED_PORT}:3000"
