version: "3"

volumes:
  db:
    driver: local
  cache:
    driver: local

services:
  database:
    image: postgres:14-alpine
    hostname: backend
    restart: unless-stopped
    volumes:
      - ../db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend
    command:
      - "postgres"
      - "-c" # Max connection limit for database.
      - "max_connections=1000" # SHOW max_connections;
      - "-c" # Buffer size for database bufferization.
      - "shared_buffers=128MB" # SHOW shared_buffers;

  cache:
    image: redis:7-alpine
    hostname: backend
    restart: unless-stopped
    command: redis-server
    volumes:
      - ../cache:/data
    networks:
      - backend

  server:
    hostname: backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backend:/srv/api
    ports:
      - "${COMPOSE_EXPOSED_PORT}:80"
    depends_on:
      - database
      - cache
    links:
      - database
      - cache
    networks:
      - backend
    build: .
    command: "python manage.py runserver 0.0.0.0:80"

networks:
  backend:
    name: backend
